name: "Bug Report"
description: "버그 리포팅을 위한 이슈 템플릿"
labels: ["bug"]
body:
  - type: input
    id: wrike_ticket_link
    attributes:
      label: "📌 유입 경로 (Wrike Ticket Link)"
      description: "예시: WK-1111111"
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "🔄 버그 재현 방법 (시나리오, 환경)"
      description: "버그를 재현하기 위한 단계를 작성해주세요."
    validations:
      required: true

  - type: textarea
    id: bug_details
    attributes:
      label: "🐛 문제 상황"
      description: "버그가 발생한 상황을 설명해주세요."

  - type: textarea
    id: expected_result
    attributes:
      label: "✅ 기대 결과 (Expected result)"
      description: "기대했던 동작을 설명해주세요."
    validations:
      required: true

  - type: textarea
    id: actual_result
    attributes:
      label: "❌ 실제 결과 (Actual result)"
      description: "실제로 발생한 동작을 설명해주세요."
    validations:
      required: true

  - type: textarea
    id: bug_cause
    attributes:
      label: "🔍 버그 원인"
      description: "버그의 원인을 설명해주세요. (reference commit 포함)"

  - type: textarea
    id: resolution
    attributes:
      label: "🛠 해결 방법"
      description: "버그를 해결하기 위한 방법을 작성해주세요."

  - type: markdown
    attributes:
      value: "<hr>\n"

  - type: textarea
    id: considerations
    attributes:
      label: "🤔 개발 중 고민했던 사항들"
      description: "개발하면서 고민했던 부분이나 코드리뷰에서 논의하고 싶은 내용을 작성해주세요."

  - type: textarea
    id: post_deployment_todo
    attributes:
      label: "📌 배포 후속 TODO"
      description: "배포 후 추가 개선되면 좋을 사항을 정리해주세요."

  - type: textarea
    id: test_guide
    attributes:
      label: "🛠 Test Guide"
      description: "제품 셋업 방법 및 테스트 방법을 설명해주세요."

  - type: textarea
    id: test_cases
    attributes:
      label: "✅ Test Cases"
      description: "테스트 케이스를 작성해주세요. Edge case도 포함하면 좋습니다."

  - type: textarea
    id: attachments
    attributes:
      label: "📷 스크린샷 / GIF 첨부"
      description: "필요한 경우 스크린샷이나 GIF를 첨부해주세요. (UI 변경 시 필수)"
      value: "<details>\n<summary>스크린샷</summary>\n\n</details>"
